name: Build_4_0_4_MacOS_10_15_x86_64

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-10.15

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out repository
      - uses: actions/checkout@v2
        with:
          ref: build-4.0.4


      # Runs a set of commands using the runners shell
      - name: Install OpenMP
        run: brew install libomp
      - name: Create bin directory
        run: mkdir bin
      - name: Build 
        run: |
          g++ *.cpp /usr/local/opt/libomp/lib/libomp.a -o bin/marzone -Xclang -fopenmp -std=c++17  -O3
      - name: Zip 
        run: |
          cd bin
          zip marzone-4.0.4-macOS-10.15-x86-64.zip marzone
          cd ..

      
      # Uploads build results to an artifact
      - uses: actions/upload-artifact@v2
        with:
          name: macos-10.15-x86-64-build
          path: bin/marzone-4.0.4-macOS-10.15-x86-64.zip